# This file was generated by the {rix} R package v0.18.2 on 2026-08-03
# with following call:
# >rix(date = "2026-06-22",
#  > r_pkgs = required_packages,
#  > system_pkgs = c("quarto",
#  > "git",
#  > "pandoc",
#  > "typst",
#  > "stanc",
#  > "tbb",
#  > "gettext",
#  > "libintl"),
#  > git_pkgs = list(list(package_name = "cmdstanr",
#  > repo_url = "https://github.com/stan-dev/cmdstanr",
#  > commit = "541f36c74c236a322eaa0908e2e86425790ca2cf"),
#  > list(package_name = "insight",
#  > repo_url = "https://github.com/easystats/insight",
#  > commit = "36917c3bedfadf901ea8b0a90c5e144ae82bcfb8"),
#  > list(package_name = "datawizard",
#  > repo_url = "https://github.com/easystats/datawizard",
#  >      commit = "b651172a20c86aca0d768b44a634c83fb146cafd"),
#  > list(package_name = "bayestestR",
#  > repo_url = "https://github.com/easystats/bayestestR",
#  > commit = "77d649a2f55481e0b863c0d35b2a14dba7f44afb"),
#  > list(package_name = "parameters",
#  > repo_url = "https://github.com/easystats/parameters",
#  > commit = "9fb4f21f2452cfb1c8e6511e0cfa521db5d7d7de"),
#  > list(package_name = "performance",
#  > repo_url = "https://github.com/easystats/performance",
#  > commit = "78c41eec5285896e8ae86776979ff7b4f41f38ae"),
#  > list(package_name = "modelbased",
#  >      repo_url = "https://github.com/easystats/modelbased",
#  > commit = "e12e4a96c396b754a6b29c1df3215c1c0057e287"),
#  > list(package_name = "cogmod",
#  > repo_url = "https://github.com/DominiqueMakowski/cogmod",
#  > commit = "4b10ea5e00e02984d39c0749adf8dc0b9c4ab15b")),
#  > tex_pkgs = c("amsmath",
#  > "ninecolors",
#  > "apa7",
#  > "scalerel",
#  > "threeparttable",
#  > "threeparttablex",
#  > "endfloat",
#  > "environ",
#  > "multirow",
#  > "tcolorbox",
#  > "pdfcol",
#  > "tikzfill",
#  > "fontawesome5",
#  > "framed",
#  > "newtx",
#  > "fontaxes",
#  > "xstring",
#  > "wrapfig",
#  > "tabularray",
#  >      "siunitx",
#  > "fvextra",
#  > "geometry",
#  > "setspace",
#  > "fancyvrb",
#  > "anyfontsize"),
#  > ide = "positron",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = "Rscript install_cmdstan.R",
#  > r_ver = "4.6.0")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-06-22.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      brms
      collapse
      emmeans
      fs
      ggdist
      ggplot2
      knitr
      marginaleffects
      patchwork
      qs2
      ragg
      reformulas
      rmarkdown
      tidyverse
      tinytable;
  };
 
    bayestestR = (pkgs.rPackages.buildRPackage {
      name = "bayestestR";
      src = pkgs.fetchgit {
        url = "https://github.com/easystats/bayestestR";
        rev = "77d649a2f55481e0b863c0d35b2a14dba7f44afb";
        sha256 = "sha256-ba7oTuTqKaaN+fl5JjmPqZFBnp7fubnAk+7Q8HlJuZY=";
      };
      propagatedBuildInputs = [ insight datawizard ];
    });

    cmdstanr = (pkgs.rPackages.buildRPackage {
      name = "cmdstanr";
      src = pkgs.fetchgit {
        url = "https://github.com/stan-dev/cmdstanr";
        rev = "541f36c74c236a322eaa0908e2e86425790ca2cf";
        sha256 = "sha256-4qf52WZ50S0PdeKVKe08jvWCegbf9H+QZCyoq7w2Xy4=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          checkmate
          data_table
          jsonlite
          posterior
          processx
          R6
          withr
          rlang;
      };
    });

    cogmod = (pkgs.rPackages.buildRPackage {
      name = "cogmod";
      src = pkgs.fetchgit {
        url = "https://github.com/DominiqueMakowski/cogmod";
        rev = "4b10ea5e00e02984d39c0749adf8dc0b9c4ab15b";
        sha256 = "sha256-/5NYMIYgvKRRAquQajXFbYxTd+SITEAOQobc+5WhbGA=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          brms;
      } ++ [ cmdstanr insight datawizard bayestestR parameters performance modelbased ];
    });

    datawizard = (pkgs.rPackages.buildRPackage {
      name = "datawizard";
      src = pkgs.fetchgit {
        url = "https://github.com/easystats/datawizard";
        rev = "b651172a20c86aca0d768b44a634c83fb146cafd";
        sha256 = "sha256-PAkNwMwce8hNgXjzwHcff9R8qMVJzhcJzLYdPh0ZShE=";
      };
      propagatedBuildInputs = [ insight ];
    });

    insight = (pkgs.rPackages.buildRPackage {
      name = "insight";
      src = pkgs.fetchgit {
        url = "https://github.com/easystats/insight";
        rev = "36917c3bedfadf901ea8b0a90c5e144ae82bcfb8";
        sha256 = "sha256-aHNmsyvPSTn+n9j2LWv2ksp9bz0DfR8xD2KtcAPsSmw=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) ;
      };
    });

    modelbased = (pkgs.rPackages.buildRPackage {
      name = "modelbased";
      src = pkgs.fetchgit {
        url = "https://github.com/easystats/modelbased";
        rev = "e12e4a96c396b754a6b29c1df3215c1c0057e287";
        sha256 = "sha256-k73qijIPWVxact3SJP7bwCchkvBFlz5j1ynhTVflmFI=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages)
          emmeans;
      } ++ [ datawizard insight parameters bayestestR ];
    });

    parameters = (pkgs.rPackages.buildRPackage {
      name = "parameters";
      src = pkgs.fetchgit {
        url = "https://github.com/easystats/parameters";
        rev = "9fb4f21f2452cfb1c8e6511e0cfa521db5d7d7de";
        sha256 = "sha256-L+SmDvgLF9pKnf54dQNXxZs/qAA+iRcuH2OKuYy6z6o=";
      };
      propagatedBuildInputs = [ datawizard insight bayestestR ];
    });

    performance = (pkgs.rPackages.buildRPackage {
      name = "performance";
      src = pkgs.fetchgit {
        url = "https://github.com/easystats/performance";
        rev = "78c41eec5285896e8ae86776979ff7b4f41f38ae";
        sha256 = "sha256-u3Hlmd1O7HxKcVyVi5kaCxrQhNwe0g5+mVClYgBuajc=";
      };
      propagatedBuildInputs = [ insight datawizard bayestestR ];
    });

  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath
      anyfontsize
      apa7
      endfloat
      environ
      fancyvrb
      fontawesome5
      fontaxes
      framed
      fvextra
      geometry
      multirow
      newtx
      ninecolors
      pdfcol
      scalerel
      setspace
      siunitx
      tabularray
      tcolorbox
      threeparttable
      threeparttablex
      tikzfill
      wrapfig
      xstring;
  });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      gettext
      git
      glibcLocales
      libintl
      nix
      pandoc
      positron-bin
      quarto
      R
      stanc
      tbb
      typst
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ cmdstanr insight datawizard bayestestR parameters performance modelbased cogmod rpkgs tex system_packages ];
    shellHook = ''
    Rscript install_cmdstan.R
  '';
  }; 
in
  {
    inherit pkgs shell;
  }
